Remove 'require('ts-node').register({files: true});' from wdio.conf.ts in the before function which caused the errors: error TS2451: Cannot redeclare block-scoped variable 'chai_1'. error TS2451: Cannot redeclare block-scoped variable 'testingData_1'. Upgrade versions in package.json